"""empty message

Revision ID: 013ca20eafb4
Revises: 80d78f1b30a8
Create Date: 2020-01-21 16:18:17.623349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013ca20eafb4'
down_revision = '80d78f1b30a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog__post', sa.Column('message', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog__post', 'message')
    # ### end Alembic commands ###
