"""empty message

Revision ID: 80d78f1b30a8
Revises: 34395f81bfbf
Create Date: 2020-01-20 19:12:26.696781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d78f1b30a8'
down_revision = '34395f81bfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog__post',
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('blog_post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog__post')
    # ### end Alembic commands ###
