"""empty message

Revision ID: a4f3964d61fd
Revises: 013ca20eafb4
Create Date: 2020-01-21 16:58:48.948848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f3964d61fd'
down_revision = '013ca20eafb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('blog_post_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=250), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog_post.blog_post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.drop_table('blog__post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog__post',
    sa.Column('blog_post_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=True),
    sa.Column('url', sa.VARCHAR(length=250), nullable=True),
    sa.Column('message', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('blog_post_id')
    )
    op.drop_table('comment')
    op.drop_table('blog_post')
    # ### end Alembic commands ###
